links:
- label: my github
  categories: ["dev"]
  url: https://github.com/zephinzer
- label: my gitlab
  categories: ["dev"]
  url: https://gitlab.com/zephinzer
- label: my medium
  categories: ["writing"]
  url: https://medium.com/@joeir
networks:
- name: internet
  check:
    url: https://google.com
repositories:
- name: my github blog
  url: git@github.com:zephinzer/blog.joeir.net.git
  workspaces: ["personal"]
- name: my knowledge wiki
  url: git@github.com:zephinzer/wiki.joeir.net.git
  workspaces: ["personal"]
- name: my dotfiles
  url: git@github.com:zephinzer/dotfiles.git
  workspaces: ["personal"]
- name: dev tool
  url: git@gitlab.com:zephinzer/dev.git
  workspaces: ["personal"]
- name: usvc website
  url: git@gitlab.com:usvc/usvc.git
  workspaces: ["usvc"]
- name: ci pipeline recipes
  url: git@gitlab.com:usvc/images/ci/recipes.git
  workspaces: ["usvc"]
- name: golang configuration package
  url: git@gitlab.com:usvc/modules/go/config.git
  workspaces: ["usvc"]
- name: golang database package
  url: git@gitlab.com:usvc/modules/go/db.git
  workspaces: ["usvc"]
- name: golang logger package
  url: git@gitlab.com:usvc/modules/go/logger.git
  workspaces: ["usvc"]
- name: golang password management package
  url: git@gitlab.com:usvc/modules/go/password.git
  workspaces: ["usvc"]
- name: golang semantic versioning package
  url: git@gitlab.com:usvc/modules/go/semver.git
  workspaces: ["usvc"]
softwares:
- name: docker
  check:
    command: ["docker", "version", "--format", "{{.Client.Platform.Name}} {{.Client.Version}}"]
    stdout: ^Docker Engine.*\d+\.\d+(\.\d+)?$
- name: golang
  check:
    command: ["go", "version"]
    stdout: ^go version go\d\.\d+(\.\d+)? [a-zA-Z0-9]+\/[a-zA-Z0-9]+$
- name: kubectl
  check:
    command: ["kubectl", "version", "--client", "--short"]
    stdout: '^Client Version: v\d+\.\d+(\.\d+)?$'
- name: node
  check:
    command: ["node", "-v"]
    stdout: ^v\d+\.\d+\.\d+$
- name: yarn
  check:
    command: ["yarn", "-v"]
    stdout: ^\d+\.\d+\.\d+$
