#!/bin/sh
TIMESTAMP=$(date +'%Y%m%d%H%M%S');
mkdir -p .archives;

#   _   _  _  _  ___ __   __ ___  ___  ___    _    _    
#  | | | || \| ||_ _|\ \ / /| __|| _ \/ __|  /_\  | |   
#  | |_| || .` | | |  \ V / | _| |   /\__ \ / _ \ | |__ 
#   \___/ |_|\_||___|  \_/  |___||_|_\|___//_/ \_\|____|
#                                                      

printf -- "Processing ${HOME}/.aliases... " \
  && [ -e ${HOME}/.aliases ] \
  && cp ./.aliases ./.archives/.aliases.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.aliases > ./.aliases \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.aliases.docker... " \
  && [ -e ${HOME}/.aliases.docker ] \
  && cp ./.aliases.docker ./.archives/.aliases.docker.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.aliases.docker > ./.aliases.docker \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.aliases.kubectl... " \
  && [ -e ${HOME}/.aliases.kubectl ] \
  && cp ./.aliases.kubectl ./.archives/.aliases.kubectl.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.aliases.kubectl > ./.aliases.kubectl \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.profile... " \
  && [ -e ${HOME}/.profile ] \
  && cp ./.profile ./.archives/.profile.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.profile > ./.profile \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

#  ___    _    ___  _  _ 
# | _ )  /_\  / __|| || |
# | _ \ / _ \ \__ \| __ |
# |___//_/ \_\|___/|_||_|
#                                               

printf -- "Processing ${HOME}/.bash_profile... " \
  && [ -e ${HOME}/.bash_profile ] \
  && cp ./.bash_profile ./.archives/.bash_profile.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.bash_profile > ./.bash_profile \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

#   ____ ___  _  _ 
#  |_  // __|| || |
#   / / \__ \| __ |
#  /___||___/|_||_|
#                 

printf -- "Processing ${HOME}/.zshrc... " \
  && [ -e ${HOME}/.zshrc ] \
  && cp ./.zshrc ./.archives/.zshrc.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.zshrc > ./.zshrc \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

# __  __ __  __   ___   ___   __  __    _    ___ 
# \ \/ /|  \/  | / _ \ |   \ |  \/  |  /_\  | _ \
#  >  < | |\/| || (_) || |) || |\/| | / _ \ |  _/
# /_/\_\|_|  |_| \___/ |___/ |_|  |_|/_/ \_\|_|  
#                                                

printf -- "Processing ${HOME}/.Xmodmap... " \
  && [ -e ${HOME}/.Xmodmap ] \
  && cp ./.Xmodmap ./.archives/.Xmodmap.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.Xmodmap > ./.Xmodmap \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';
