#!/bin/sh
TIMESTAMP=$(date +'%Y%m%d%H%M%S');
mkdir -p .archives
cp ./.profile ./.archives/.profile.snapshot_on.${TIMESTAMP};
cat ~/.profile > ./.profile;
cp ./.zshrc ./.archives/.zshrc.snapshot_on.${TIMESTAMP};
cat ~/.zshrc > ./.zshrc;
cp ./.bash_profile ./.archives/.bash_profile.snapshot_on.${TIMESTAMP};
cat ~/.bash_profile > ./.bash_profile
