define HELP
Ghost is a blogging platform

Docker Hub: https://hub.docker.com/_/ghost
Official Site: https://ghost.org/

Ghost Usage
^^^^^^^^^^^

make:
  init_helm - this initialises the helm repository from Bitnami
	install_helm - this installs the latest Ghost helm chart

endef

include ../_/Makefile

init_helm:

install_helm:
	
