version: "3.7"
services:
  postgresql:
    image: postgres:13.2-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data.d/postgresql:/var/lib/postgresql/data
  keycloak:
      image: quay.io/keycloak/keycloak:16.1.1
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgresql
        DB_DATABASE: keycloak
        DB_USER: user
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
      ports:
        - 8080:8080
      depends_on:
        - postgresql
