kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.16.0.0/16"
  serviceSubnet: "10.15.0.0/16"
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: ./data/worker0
    containerPath: /data
- role: worker
  extraMounts:
  - hostPath: ./data/worker1
    containerPath: /data
