#!/bin/bash
if [ "$(id -u)" != "0" ]; then
  printf -- '\033[31mrun this script as root\033[0m\n';
  exit 1;
fi;

rm -rf /usr/local/bin/__kb;
which __kb || ln -s "$(pwd)/bin/__kb" /usr/local/bin/__kb;

rm -rf /usr/local/bin/__m;
which __m || ln -s "$(pwd)/bin/__m" /usr/local/bin/__m;

rm -rf /usr/local/bin/__pw;
which __pw || ln -s "$(pwd)/bin/__pw" /usr/local/bin/__pw;

rm -rf /usr/local/bin/pbcopy;
which pbcopy || ln -s "$(pwd)/bin/pbcopy" /usr/local/bin/pbcopy;

rm -rf /usr/local/bin/__ualt;
which update-alternatives && ln -s $(pwd)/bin/ualt /usr/local/bin/__ualt;
