#!/bin/sh
TIMESTAMP=$(date +'%Y%m%d%H%M%S');
mkdir -p .archives;

#   _   _  _  _  ___ __   __ ___  ___  ___    _    _    
#  | | | || \| ||_ _|\ \ / /| __|| _ \/ __|  /_\  | |   
#  | |_| || .` | | |  \ V / | _| |   /\__ \ / _ \ | |__ 
#   \___/ |_|\_||___|  \_/  |___||_|_\|___//_/ \_\|____|
#                                                      

printf -- "Processing ${HOME}/.aliases... " \
  && [ -e ${HOME}/.aliases ] \
  && cp ./.aliases \
  && cp ./.aliases ./.archives/.aliases.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.aliases > ./.aliases \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.aliases_docker... " \
  && [ -e ${HOME}/.aliases_docker ] \
  && touch ./.aliases_docker \
  && cp ./.aliases_docker ./.archives/.aliases_docker.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.aliases_docker > ./.aliases_docker \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.aliases_git... " \
  && [ -e ${HOME}/.aliases_git ] \
  && touch ./.aliases_git \
  && cp ./.aliases_git ./.archives/.aliases_git.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.aliases_git > ./.aliases_git \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.aliases_kubectl... " \
  && [ -e ${HOME}/.aliases_kubectl ] \
  && touch ./.aliases_kubectl \
  && cp ./.aliases_kubectl ./.archives/.aliases_kubectl.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.aliases_kubectl > ./.aliases_kubectl \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.bash_profile... " \
  && [ -e ${HOME}/.bash_profile ] \
  && touch ./.bash_profile \
  && cp ./.bash_profile ./.archives/.bash_profile.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.bash_profile > ./.bash_profile \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.gitconfig... " \
  && [ -e ${HOME}/.gitconfig ] \
  && touch ./.gitconfig \
  && cp ./.gitconfig ./.archives/.gitconfig.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.gitconfig > ./.gitconfig \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.profile... " \
  && [ -e ${HOME}/.profile ] \
  && touch ./.profile \
  && cp ./.profile ./.archives/.profile.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.profile > ./.profile \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.vimrc... " \
  && [ -e ${HOME}/.vimrc ] \
  && touch ./.vimrc \
  && cp ./.vimrc ./.archives/.vimrc.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.vimrc > ./.vimrc \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.Xmodmap... " \
  && [ -e ${HOME}/.Xmodmap ] \
  && touch ./.Xmodmap \
  && cp ./.Xmodmap ./.archives/.Xmodmap.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.Xmodmap > ./.Xmodmap \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';

printf -- "Processing ${HOME}/.zshrc... " \
  && [ -e ${HOME}/.zshrc ] \
  && touch ./.zshrc \
  && cp ./.zshrc ./.archives/.zshrc.snapshot_on.${TIMESTAMP} \
  && cat ${HOME}/.zshrc > ./.zshrc \
  && printf -- 'DONE.\n' \
  || printf -- 'SKIPPED.\n';
